### ISSUE TITLE
Correct regular expresion

### ISSUE THREAD

**Issue by ErickChacon** [ruimanzhong/spfc#16]
The regular expresion assumes that the user introduces spaces in `model = "rw1"`, it can be the case that they do not include spaces or maybe include in one side. We need to modify the regular expression to cover those cases.

https://github.com/ruimanzhong/bsfc/blob/41131d1d10954ddc6c4e913c35f6209d0b0ebe2a/R/model-within.R#L172-L174

Note: Be consistent with the coding style, for example do not introduce `=` instead of `<-`.

**Comment by ruimanzhong** [comment]
The package is for visualization, if we will not use ggraph, we could remove it. Right now, we could remove it
